title: nz420
description: little bits of this and that
url: https://joefizz.github.io

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
theme: jekyll-theme-midnight

plugins:
  - jekyll-feed